### ISSUE TITLE
Некоторые миры хранят регионы в доп. папке DIM-*

### ISSUE THREAD

**Issue by gomin1d** [lokha/mega-chunk-fixer-2000#1]

**Comment by SPYmesu** [comment]
Это не доп папки, а измерения - ад и край. Такие папки характерны лишь для карт, созданных для одиночной игры. DIM1 (Положительное число - край), DIM-1 (Отрицательное число - ад).

**Comment by gomin1d** [comment]
@SPYmeYT 
Один цикл работы программы работает с одним миром, по сути с одной папкой регионов.  
А DIM1 и DIM-1 это полноценные миры, хоть и находятся в папке основного мира.

Чтобы просканировать их, можно указать путь именно к ним:  
*  `java -jar mega-chunk-fixer-2000.jar world`
*  `java -jar mega-chunk-fixer-2000.jar world/DIM1`
*  `java -jar mega-chunk-fixer-2000.jar world/DIM-1`

Пусть эта задача лежит на пользователе, не хочу усложнять спецификацию цикла работы программы.
